server.port=${PORT:8080}
spring.application.name=comfortFootwear

# ===============================
# MySQL
# ===============================

spring.datasource.url=${TIDB_URL}
spring.datasource.username=${TIDB_USERNAME}
spring.datasource.password=${TIDB_PASSWORD}
# spring.datasource.url=jdbc:mysql://localhost:3306/comfort_footwear_db
# spring.datasource.username=root
# spring.datasource.password=Ritesh@8219

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# jwt
# ===============================

jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}
jwt.expiry=${JWT_EXPIRY}

# ===============================
# Google OAuth2
# ===============================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# spring.config.import=optional:file:Backend/.env[.properties]
spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.security.oauth2.client=DEBUG