server.port=${PORT:8080}
spring.application.name=comfortFootwear

# ===============================
# MySQL
# ===============================

spring.datasource.url=${TIDB_URL}
spring.datasource.username=${TIDB_USERNAME}
spring.datasource.password=${TIDB_PASSWORD}

# HikariCP Connection Pool Optimization
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=30000

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# jwt
# ===============================

jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER}
jwt.expiry=${JWT_EXPIRY}

# ===============================
# Google OAuth2
# ===============================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# spring.config.import=optional:file:Backend/.env[.properties]
spring.config.import=optional:file:.env[.properties]

app.frontend.url=${FRONTEND_URL:http://localhost:5173}

logging.level.org.springframework.security.oauth2.client=DEBUG